language: java
sudo: false
#install: true

jdk:
  - oraclejdk8

#script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  #- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
#  - sonar-scanner

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'


addons:
  sonarqub
   token:
      secure: "W3O12OhzSulPJlrYCc/FgHLJY82EmnGBrhZcNRyPyJvJ0DdfndOUfmEld3SW50IB2jN1earw4AdajrgXIjbbvou4wghcxJqTYJzSwUKC5f/JBXf2kiTqo4lCu5OG4XOw2kwkMWfC9NTa4Qga0rg2ERLp/N8bOq8/h7T7PQKsiKp9STQrdiiFK8xUiTC1dpQSJjS3eQlD8rNxX6DVmErSqnamMPGB0k8agpsTTC5o0oOD2D4Qt3n66dJSw0KgZJq7o0v7avW7OgG84AmRV/nkmMivOQPn7wv/Rn6zeFNnryOjNRu3bxAALe3sCrPTa4EHu1Kd3tKwRb2yrgExODsaiV9ashDjM8+DTyanBTBfdhTzNm9q7OJUVEGYdVjTNkXlYpW7i1BAvoJVnrvo/KnZWXJT/fJqk5E+1dTd+zzHrKrG9ZPH/sXbFJ/Wfc9GqXCR4tL2MhX6mcSvupdceLaF1BCcQ4YSN3OHthC2zr7FX1EvUTzKBdetqILjO7XgbliL0tyqOz7mI3H1b+xGF4bVQRVJEilnIBwb3f5tgsiG49PiG3q6i3KaNxGCZ9iOkht/b9B2ayuP2h2o7fe8j98EsQjuINZ5U3rFsO0yB7f2qty0CUfmLULpGTdAwuK0bC1iO9aR8S0UAZBizgit8w/52mbp+X7JDoyveHWxksXkuVk="

install:
- mvn dependency:go-offline
script:
- mvn verify site sonar:sonar -Dmaven.test.failure.ignore=true


notifications:
  email: false
