language: java
sudo: false
#install: true

jdk:
  - oraclejdk8

#script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  #- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
#  - sonar-scanner

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'


addons:
  sonarqube:
   token:
      secure: "W3O12OhzSulPJlrYCc/FgHLJY82EmnGBrhZcNRyPyJvJ0DdfndOUfmEld3SW50IB2jN1earw4AdajrgXIjbbvou4wghcxJqTYJzSwUKC5f/JBXf2kiTqo4lCu5OG4XOw2kwkMWfC9NTa4Qga0rg2ERLp/N8bOq8/h7T7PQKsiKp9STQrdiiFK8xUiTC1dpQSJjS3eQlD8rNxX6DVmErSqnamMPGB0k8agpsTTC5o0oOD2D4Qt3n66dJSw0KgZJq7o0v7avW7OgG84AmRV/nkmMivOQPn7wv/Rn6zeFNnryOjNRu3bxAALe3sCrPTa4EHu1Kd3tKwRb2yrgExODsaiV9ashDjM8+DTyanBTBfdhTzNm9q7OJUVEGYdVjTNkXlYpW7i1BAvoJVnrvo/KnZWXJT/fJqk5E+1dTd+zzHrKrG9ZPH/sXbFJ/Wfc9GqXCR4tL2MhX6mcSvupdceLaF1BCcQ4YSN3OHthC2zr7FX1EvUTzKBdetqILjO7XgbliL0tyqOz7mI3H1b+xGF4bVQRVJEilnIBwb3f5tgsiG49PiG3q6i3KaNxGCZ9iOkht/b9B2ayuP2h2o7fe8j98EsQjuINZ5U3rFsO0yB7f2qty0CUfmLULpGTdAwuK0bC1iO9aR8S0UAZBizgit8w/52mbp+X7JDoyveHWxksXkuVk="
      secure: "kbjtXs191zWaVmuTnmls0nOVRx2P2d58dd43YqtsC4/hkmx0pBQPgadHL8urI5JvQkwCf7weFaJGJSteFdwUyFPgjLT/1i9FsJpP05TnM5udQgZXpvVMtQdZHmtQW5hBor3112rUaz0ZRc8jd6MTTKSik88el3EeKeHofOlHT1DAPQVkyZDJnXrusuwlMIkdVCA4M6q+3YUh6giewvB8ArDTntUATgaOzGZgZEic1XkruFUX6eGCk125luq8f6NVV94gUeexSw/rOW6PXyiIPgbXqMZojN63E1ryHWdlwsjlAkYOjNBECsekUo/NHT+harYpJtdfoRUx64vxLdqCxMo77HlYRm1jmQFUilAIlnBXzTjPkrzcsX2ouY01T/iGHi/DfY3yb6x87ZUFOM/bQ3IfIvK53040eCUMGLCOuC9cpiCvAm0rm1qorXXIp2l8snUlbpoWp5A8KJFNce8x2EuCTCJrsD93icQihH4z3u8gj/elvZgMLM6e4MTHo70lMTNVIyEhwg4bUabcRkekNsKxcWlrDBAnljo9Mmrz98tVtCIw8wT3Ab6NPv2+vKY9TQqLDnOrKe189kzrf1s5j0ifHoSx0HQbj31VgJqbpoV653tBxfP4G5rDKCNWrpL8z/Isg0PEsu2WLjjJAHDdknHUjVqw+e3razThcmeEt1g="

install:
- mvn dependency:go-offline
script:
- mvn verify site sonar:sonar -Dmaven.test.failure.ignore=true


notifications:
  email: false
